services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: veyli-admin
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8088:8000"
    environment:
      API_BASE_URL: ${API_BASE_URL:-http://host.docker.internal:8001/api/v1}
      API_TIMEOUT: ${API_TIMEOUT:-15}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  node:
    image: node:20
    container_name: veyli_node
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    depends_on:
      - app
